### ISSUE TITLE
Allow perfect records?

### ISSUE THREAD

**Issue by dwt** [xiaodaigh/baduk-go-weiqi-ratings#5]
Not sure I’m reading this correctly, as my Julia skills are quasi non existing.

but this code seems to exclude the possibility that a player has a perfect record and wins every time? 

https://github.com/xiaodaigh/baduk-go-weiqi-ratings/blob/9a44e88b1796a73622e0389bcce35815d42f7a48/utils.jl#L44

probably not relevant, but still?

**Comment by xiaodaigh** [comment]
exactly 0 people have had perfect record over 365 days unless they played very few games

**Comment by xiaodaigh** [comment]
also we should just use https://github.com/xiaodaigh/baduk-go-weiqi-ratings/discussions 

and keep issues for bug reports.
